// <auto-generated />
using System;
using System.Collections.Generic;
using CoinLeopard.DB.Ticks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoinLeopard.DB.Ticks.Migrations
{
    [DbContext(typeof(TickDbContext))]
    partial class TickDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Aggregates.AggregateKline10", b =>
                {
                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("AggregateKline10", (string)null);

                    b
                        .HasAnnotation("TimescaleDB:AggregateFunctions", new List<string> { "OpenTime:Min:OpenTime", "OpenPrice:First:OpenPrice", "HighPrice:Max:HighPrice", "LowPrice:Min:LowPrice", "ClosePrice:Last:ClosePrice", "Volume:Sum:Volume", "CloseTime:Max:CloseTime", "QuoteVolume:Sum:QuoteVolume", "TradeCount:Sum:TradeCount", "TakerBuyBaseVolume:Sum:TakerBuyBaseVolume", "TakerBuyQuoteVolume:Sum:TakerBuyQuoteVolume" })
                        .HasAnnotation("TimescaleDB:ChunkInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:CreateGroupIndexes", true)
                        .HasAnnotation("TimescaleDB:GroupByColumns", new List<string> { "Symbol" })
                        .HasAnnotation("TimescaleDB:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDB:MaterializedViewName", "AggregateKline10")
                        .HasAnnotation("TimescaleDB:ParentName", "Kline")
                        .HasAnnotation("TimescaleDB:TimeBucket:BucketWidth", "10 minutes")
                        .HasAnnotation("TimescaleDB:TimeBucket:GroupBy", true)
                        .HasAnnotation("TimescaleDB:TimeBucket:SourceColumn", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Aggregates.AggregateKline1440", b =>
                {
                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("AggregateKline1440", (string)null);

                    b
                        .HasAnnotation("TimescaleDB:AggregateFunctions", new List<string> { "OpenTime:Min:OpenTime", "OpenPrice:First:OpenPrice", "HighPrice:Max:HighPrice", "LowPrice:Min:LowPrice", "ClosePrice:Last:ClosePrice", "Volume:Sum:Volume", "CloseTime:Max:CloseTime", "QuoteVolume:Sum:QuoteVolume", "TradeCount:Sum:TradeCount", "TakerBuyBaseVolume:Sum:TakerBuyBaseVolume", "TakerBuyQuoteVolume:Sum:TakerBuyQuoteVolume" })
                        .HasAnnotation("TimescaleDB:ChunkInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:CreateGroupIndexes", true)
                        .HasAnnotation("TimescaleDB:GroupByColumns", new List<string> { "Symbol" })
                        .HasAnnotation("TimescaleDB:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDB:MaterializedViewName", "AggregateKline1440")
                        .HasAnnotation("TimescaleDB:ParentName", "Kline")
                        .HasAnnotation("TimescaleDB:TimeBucket:BucketWidth", "1 day")
                        .HasAnnotation("TimescaleDB:TimeBucket:GroupBy", true)
                        .HasAnnotation("TimescaleDB:TimeBucket:SourceColumn", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Aggregates.AggregateKline240", b =>
                {
                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("AggregateKline240", (string)null);

                    b
                        .HasAnnotation("TimescaleDB:AggregateFunctions", new List<string> { "OpenTime:Min:OpenTime", "OpenPrice:First:OpenPrice", "HighPrice:Max:HighPrice", "LowPrice:Min:LowPrice", "ClosePrice:Last:ClosePrice", "Volume:Sum:Volume", "CloseTime:Max:CloseTime", "QuoteVolume:Sum:QuoteVolume", "TradeCount:Sum:TradeCount", "TakerBuyBaseVolume:Sum:TakerBuyBaseVolume", "TakerBuyQuoteVolume:Sum:TakerBuyQuoteVolume" })
                        .HasAnnotation("TimescaleDB:ChunkInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:CreateGroupIndexes", true)
                        .HasAnnotation("TimescaleDB:GroupByColumns", new List<string> { "Symbol" })
                        .HasAnnotation("TimescaleDB:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDB:MaterializedViewName", "AggregateKline240")
                        .HasAnnotation("TimescaleDB:ParentName", "Kline")
                        .HasAnnotation("TimescaleDB:TimeBucket:BucketWidth", "4 hours")
                        .HasAnnotation("TimescaleDB:TimeBucket:GroupBy", true)
                        .HasAnnotation("TimescaleDB:TimeBucket:SourceColumn", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Aggregates.AggregateKline30", b =>
                {
                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("AggregateKline30", (string)null);

                    b
                        .HasAnnotation("TimescaleDB:AggregateFunctions", new List<string> { "OpenTime:Min:OpenTime", "OpenPrice:First:OpenPrice", "HighPrice:Max:HighPrice", "LowPrice:Min:LowPrice", "ClosePrice:Last:ClosePrice", "Volume:Sum:Volume", "CloseTime:Max:CloseTime", "QuoteVolume:Sum:QuoteVolume", "TradeCount:Sum:TradeCount", "TakerBuyBaseVolume:Sum:TakerBuyBaseVolume", "TakerBuyQuoteVolume:Sum:TakerBuyQuoteVolume" })
                        .HasAnnotation("TimescaleDB:ChunkInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:CreateGroupIndexes", true)
                        .HasAnnotation("TimescaleDB:GroupByColumns", new List<string> { "Symbol" })
                        .HasAnnotation("TimescaleDB:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDB:MaterializedViewName", "AggregateKline30")
                        .HasAnnotation("TimescaleDB:ParentName", "Kline")
                        .HasAnnotation("TimescaleDB:TimeBucket:BucketWidth", "30 minutes")
                        .HasAnnotation("TimescaleDB:TimeBucket:GroupBy", true)
                        .HasAnnotation("TimescaleDB:TimeBucket:SourceColumn", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Aggregates.AggregateKline5", b =>
                {
                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("AggregateKline5", (string)null);

                    b
                        .HasAnnotation("TimescaleDB:AggregateFunctions", new List<string> { "OpenTime:Min:OpenTime", "OpenPrice:First:OpenPrice", "HighPrice:Max:HighPrice", "LowPrice:Min:LowPrice", "ClosePrice:Last:ClosePrice", "Volume:Sum:Volume", "CloseTime:Max:CloseTime", "QuoteVolume:Sum:QuoteVolume", "TradeCount:Sum:TradeCount", "TakerBuyBaseVolume:Sum:TakerBuyBaseVolume", "TakerBuyQuoteVolume:Sum:TakerBuyQuoteVolume" })
                        .HasAnnotation("TimescaleDB:ChunkInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:CreateGroupIndexes", true)
                        .HasAnnotation("TimescaleDB:GroupByColumns", new List<string> { "Symbol" })
                        .HasAnnotation("TimescaleDB:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDB:MaterializedViewName", "AggregateKline5")
                        .HasAnnotation("TimescaleDB:ParentName", "Kline")
                        .HasAnnotation("TimescaleDB:TimeBucket:BucketWidth", "5 minutes")
                        .HasAnnotation("TimescaleDB:TimeBucket:GroupBy", true)
                        .HasAnnotation("TimescaleDB:TimeBucket:SourceColumn", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Aggregates.AggregateKline60", b =>
                {
                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("AggregateKline60", (string)null);

                    b
                        .HasAnnotation("TimescaleDB:AggregateFunctions", new List<string> { "OpenTime:Min:OpenTime", "OpenPrice:First:OpenPrice", "HighPrice:Max:HighPrice", "LowPrice:Min:LowPrice", "ClosePrice:Last:ClosePrice", "Volume:Sum:Volume", "CloseTime:Max:CloseTime", "QuoteVolume:Sum:QuoteVolume", "TradeCount:Sum:TradeCount", "TakerBuyBaseVolume:Sum:TakerBuyBaseVolume", "TakerBuyQuoteVolume:Sum:TakerBuyQuoteVolume" })
                        .HasAnnotation("TimescaleDB:ChunkInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:CreateGroupIndexes", true)
                        .HasAnnotation("TimescaleDB:GroupByColumns", new List<string> { "Symbol" })
                        .HasAnnotation("TimescaleDB:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDB:MaterializedViewName", "AggregateKline60")
                        .HasAnnotation("TimescaleDB:ParentName", "Kline")
                        .HasAnnotation("TimescaleDB:TimeBucket:BucketWidth", "1 hour")
                        .HasAnnotation("TimescaleDB:TimeBucket:GroupBy", true)
                        .HasAnnotation("TimescaleDB:TimeBucket:SourceColumn", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Aggregates.AggregateKline600", b =>
                {
                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bucket");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("AggregateKline600", (string)null);

                    b
                        .HasAnnotation("TimescaleDB:AggregateFunctions", new List<string> { "OpenTime:Min:OpenTime", "OpenPrice:First:OpenPrice", "HighPrice:Max:HighPrice", "LowPrice:Min:LowPrice", "ClosePrice:Last:ClosePrice", "Volume:Sum:Volume", "CloseTime:Max:CloseTime", "QuoteVolume:Sum:QuoteVolume", "TradeCount:Sum:TradeCount", "TakerBuyBaseVolume:Sum:TakerBuyBaseVolume", "TakerBuyQuoteVolume:Sum:TakerBuyQuoteVolume" })
                        .HasAnnotation("TimescaleDB:ChunkInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:CreateGroupIndexes", true)
                        .HasAnnotation("TimescaleDB:GroupByColumns", new List<string> { "Symbol" })
                        .HasAnnotation("TimescaleDB:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDB:MaterializedViewName", "AggregateKline600")
                        .HasAnnotation("TimescaleDB:ParentName", "Kline")
                        .HasAnnotation("TimescaleDB:TimeBucket:BucketWidth", "10 hours")
                        .HasAnnotation("TimescaleDB:TimeBucket:GroupBy", true)
                        .HasAnnotation("TimescaleDB:TimeBucket:SourceColumn", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Entities.Kline", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Symbol", "OpenTime");

                    b.HasIndex("Symbol", "OpenTime");

                    b.ToTable("Klines");

                    b
                        .HasAnnotation("TimescaleDB:ChunkTimeInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:HasRetentionPolicy", true)
                        .HasAnnotation("TimescaleDB:IsHypertable", true)
                        .HasAnnotation("TimescaleDB:RetentionPolicy:DropAfter", "30 days")
                        .HasAnnotation("TimescaleDB:TimeColumnName", "OpenTime");
                });

            modelBuilder.Entity("CoinLeopard.DB.Ticks.Entities.KlineTick", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<DateTime>("TickTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Symbol", "TickTime");

                    b.HasIndex("Symbol", "TickTime");

                    b.ToTable("KlineTicks");

                    b
                        .HasAnnotation("TimescaleDB:ChunkTimeInterval", "1 hour")
                        .HasAnnotation("TimescaleDB:HasRetentionPolicy", true)
                        .HasAnnotation("TimescaleDB:IsHypertable", true)
                        .HasAnnotation("TimescaleDB:RetentionPolicy:DropAfter", "30 days")
                        .HasAnnotation("TimescaleDB:TimeColumnName", "TickTime");
                });
#pragma warning restore 612, 618
        }
    }
}
