name: Nuget-Dev

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Get Version
        id: package_version
        uses: kzrnm/get-net-sdk-project-versions-action@v1.1.1
        with:
          proj-path: src/CoinLeopard.DB.Extensions.PostgreSQL/CoinLeopard.DB.Extensions.PostgreSQL.csproj

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack src/CoinLeopard.DB.Extensions.PostgreSQL/CoinLeopard.DB.Extensions.PostgreSQL.csproj --configuration Release --no-build --output . -p:Version=${{ steps.package_version.outputs.version }}-${{ github.run_number }}

      - name: Push
        run: dotnet nuget push "*.nupkg" --source "https://nuget.pkg.github.com/coin-leopard/index.json" --api-key ${{ secrets.PAT }}
